FROM moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION:-8.0}
#Set the shell to bash (so we can source thing)
SHELL ["/bin/bash", "-c"]
RUN apt update
#On slow net python fail with "libpython3.9-stdlib connection timed out"
RUN apt install -y python3 wget || apt install -y python3 wget
RUN curl -o - https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
RUN source ~/.nvm/nvm.sh && nvm install --lts && nvm use --lts