#!/usr/bin/env bash
height=15
width=60
listheight=16
yesno='1 Yes 0 No'

 PLUGIN_TYPE_DIALOG='--radiolist "Select plugin type (Space select, Enter confirm)" $height $width $listheight \
"mod" "Activity module" ON \
"tool" "Admin tool" OFF \
"gradingform" "Advanced grading method" OFF \
"antivirus" "Antivirus plugin" OFF \
"assignfeedback" "Assignment / Feedback plugin" OFF \
"assignsubmission" "Assignment / Submission plugin" OFF \
"assignment" "Assignment 2.2 (Disabled) / assignment" OFF \
"atto" "Atto HTML editor / Atto plugin" OFF \
"auth" "Authentication method" OFF \
"availability" "Availability restriction" OFF \
"block" "Block" OFF \
"booktool" "Book / Book tool" OFF \
"cachelock" "Cache lock handler" OFF \
"cachestore" "Cache store" OFF \
"calendartype" "Calendar type" OFF \
"contenttype" "contenttype" OFF \
"format" "Course format" OFF \
"coursereport" "Course report" OFF \
"customcertelement" "Custom certificate / customcertelement" OFF \
"customfield" "Custom field" OFF \
"dataformat" "Data format" OFF \
"datafield" "Database / Database field type" OFF \
"datapreset" "Database / Preset" OFF \
"fileconverter" "Document converter" OFF \
"editor" "Editor" OFF \
"enrol" "Enrolment method" OFF \
"ltiservice" "External tool / LTI service" OFF \
"ltisource" "External tool / LTI source" OFF \
"forumreport" "Forum / forumreport" OFF \
"grade" "Grade  method" OFF \
"gradeimport" "Grade import method" OFF \
"gradereport" "Gradebook report" OFF \
"h5plib" "H5P framework" OFF \
"local" "Local plugin" OFF \
"logstore" "Log store manager / Log store" OFF \
"mlbackend" "Machine learning backend" OFF \
"media" "Media player" OFF \
"metadatacontext" "Metadata / Data context plugin" OFF \
"metadatafieldtype" "Metadata / Data fieldtype plugin" OFF \
"mnetservice" "MNet service" OFF \
"message" "Notification plugin" OFF \
"plagiarism" "Plagiarism plugin" OFF \
"portfolio" "Portfolio" OFF \
"profilefield" "Profile field type" OFF \
"qbehaviour" "Question behaviour" OFF \
"qformat" "Question import/ format" OFF \
"qtype" "Question type" OFF \
"quizaccess" "Quiz / Access rule" OFF \
"quiz" "Quiz / Report" OFF \
"repository" "Repository" OFF \
"scormreport" "SCORM package / Report" OFF \
"search" "Search engine" OFF \
"report" "Site report" OFF \
"filter" "Text filter" OFF \
"theme" "Theme" OFF \
"tinymce" "TinyMCE HTML editor / Plugin" OFF \
"webservice" "Webservice protocol" OFF \
"workshopeval" "Workshop / Grading evaluation method" OFF \
"workshopform" "Workshop / Grading strategy" OFF \
"workshopallocation" "Workshop / Submissions allocation method" OFF \
'

 PLUGIN_COMPONENT_NAME_DIALOG='--inputbox "Component name" $height $width'
 PLUGIN_DISPLAY_NAME_DIALOG='--inputbox "Display name" $height $width'


 PLUGIN_FEATURES_DIALOG='--checklist "Select features (Space select, Enter confirm)" $height $width $listheight  \
"install" "db/install.php" ON \
"uninstall" "db/uninstall.php" OFF \
"settings" "settings.php" ON \
"readme" "README.md" ON \
"license" "LICENSE.md" OFF \
"upgrade" "db/upgrade.php" OFF \
"upgradelib" "db/upgradelib.php" OFF \
'


PLUGIN_PRIVACY_DIALOG='--menu "Does your plugin store personal user data?" $height $width $listheight $yesno'

 PLUGIN_REQUIRES_VERSION_DIALOG='--radiolist "Select a minimium required moodle verion (Space select, Enter confirm)" $height $width $listheight \
"2021051700" "3.11" ON \
"2020110900" "3.10" OFF \
"2020061500" "3.9" OFF \
"2019111800" "3.8" OFF \
"2019052000" "3.7" OFF \
"2018120300" "3.6" OFF \
"2018051700" "3.5" OFF \
"2017111300" "3.4" OFF \
"2017051500" "3.3" OFF \
"2016120500" "3.2" OFF \
"2016052300" "3.1" OFF \
"2015111600" "3.0" OFF \
"2015051100" "2.9" OFF \
"2014111000" "2.8" OFF \
"2014051200" "2.7" OFF \
"2013111800" "2.6" OFF \
"2013051400" "2.5" OFF \
"2012120300" "2.4" OFF \
"2012062500" "2.3" OFF \
"2011120500" "2.2" OFF \
'

 PLUGIN_RELEASE_DIALOG='--inputbox "Plugin release" $height $width 0.1.0'
 PLUGIN_VERSION_DIALOG='--inputbox "Plugin version" $height $width '"$(date +'%Y%m%d')"00


 PLUGIN_MATURITY_DIALOG='--checklist "Select maturiy level (Space select, Enter confirm)" $height $width $listheight  \
"MATURITY_ALPHA" "MATURITY_ALPHA" ON \
"MATURITY_BETA" "MATURITY_BETA" OFF \
"MATURITY_RC" "MATURITY_RC" OFF \
"MATURITY_STABLE" "MATURITY_STABLE" OFF \
'

PLUGIN_CLI_DIALOG='--inputmenu "Add cli script? (edit the name to add)" $height $width $listheight 1 "" 2 "" 3 "" 4 "" 5 "" '

PLUGIN_CREATE_DIALOG='--menu "How do you want to continue?" $height $width $listheight  2 "Create the plugin now" 1 "Edit the recipe manualy"'
PLUGIN_GIT_DIALOG='--menu "Initialize a GIT repository?" $height $width $listheight $yesno'
PLUGIN_GRUNT_DIALOG='--menu "Initialize GRUNT for this plugin?" $height $width $listheight $yesno'

